### ISSUE TITLE
QDriverStation detects joysticks but doesn't send to robot

### ISSUE THREAD

**Issue by retrodaredevil** [FRC-Utilities/QDriverStation#57]
Information on what I'm running:
Log created on:      Jan 24 2018 - 18:34:53 PM
LibDS version:       2.2
Operating System:    Ubuntu 16.04.3 LTS
Application name:    QDriverStation
Application version: 18.01

The problem is the same as this: https://github.com/FRC-Utilities/QDriverStation/issues/46 except on linux. The log connects, enables, disable the robot fine and the SmartDashboard even works perfectly except when I try to use a joystick on it, it detects it, but doesn't send it and I get an error when I call a joystick.getButton() in my code.

The log doesn't have any errors in it, just debug although I'd be happy to add other log files if that would help.

Another thing that would be nice is to be able to see the ports that the joysticks are on since right now it just shows a list of joysticks. I've tried this with a ps4 controller and a generic joystick. I've only tested this on my computer but I have yet to get the controllers working.

**Comment by alex-spataru** [comment]
Could you try to use the virtual joystick to control your robot (and report back the results)? This can help me to know if this is an issue with SDL, or with the LibDS library itself.

Thanks!

**Comment by retrodaredevil** [comment]
Tested it with virtual joystick and nothing.

**Comment by fearxzombie** [comment]
Same problem here, on Elementary OS Loki.

**Comment by alex-spataru** [comment]
Sorry for the late reply. Maybe the communication protocol has changed a little bit since last year, hopefully this is not the case.

**Comment by fearxzombie** [comment]
I think it probably is the case, because the robots I tested it with were 2018 robots
		
		

		-Gabriel McMillan
	




On Sat, Feb 3, 2018 at 6:24 PM -0800, "Alex Spataru" <notifications@github.com> wrote:












Sorry for the late reply. Maybe the communication protocol has changed a little bit since last year, hopefully this is not the case.

**Comment by alex-spataru** [comment]
Does your team still have access to 2015-2017 robots? If so, could you please try controling those robots with the QDriverStation?

Unfortunately, I am not into FRC anymore due to college, which makes testing LibDS and QDriverStation very difficult for me.

**Comment by fearxzombie** [comment]
I do, however it will be a while before I can test it, I will get back to you on that.
		
		

		-Gabriel McMillan
	




On Sat, Feb 3, 2018 at 6:34 PM -0800, "Alex Spataru" <notifications@github.com> wrote:












Does your team still have access to 2015-2017 robots? If so, could you please try controling those robots with the QDriverStation?


Unfortunately, I am not into FRC anymore due to college, which makes testing LibDS and QDriverStation very difficult for me.

**Comment by eamonniknafs** [comment]
I have a 2016 robot and a current one. I’ll check on that on Monday, if no one has by then.

**Comment by fearxzombie** [comment]
Got it.
		
		

		-Gabriel McMillan
	




On Sat, Feb 3, 2018 at 6:39 PM -0800, "Eamon Niknafs" <notifications@github.com> wrote:










I have a 2016 robot and a current one. I’ll check on that on Monday, if no one has by then.

**Comment by alex-spataru** [comment]
We'll move discussion of this issue to #58, which deals with the 2018 protocol implementation. Thanks for the reports!
